### ISSUE TITLE
literally lacks everything

### ISSUE THREAD

**Issue by CodingBobby** [Bumbleboss/bumble-standard#1]
The issue is, that you can't do anything smart with this, it's ******** ***** ****** ** ****** ****.

**Comment by Bumbleboss** [comment]
Thanks for your very _very_ fruitful feedback. I will greatly take this into consideration, speaking of which, yours does even worse!

**Comment by CodingBobby** [comment]
I was kind enough to peep out some words as they were potentially harmful to your sweet dreams. A** **** ***** ******!

**Comment by Bumbleboss** [comment]
I'm sorry you had to go through peeping out the words, oh wait... You just can't handle them yourself.
